import type { UserScopedTable } from "../userScopedTables";

export const MEETING_USER_SCOPED_TABLES = [
  {
    table: "meetingSessions",
    userIdIndex: "by_user_meeting",
    byThreadOnly: false,
    hasStorageBlobs: false,
    purgeOnDelete: true,
    transferOnUpgrade: true,
    exportPersonalData: true,
    exportKey: "meetingSessions",
  },
  {
    table: "meetingTranscriptSegments",
    userIdIndex: "by_user_meeting_sequence",
    byThreadOnly: false,
    hasStorageBlobs: false,
    purgeOnDelete: true,
    transferOnUpgrade: true,
    exportPersonalData: true,
    exportKey: "meetingTranscriptSegments",
  },
  {
    table: "meetingContexts",
    userIdIndex: "by_user_meeting_created",
    byThreadOnly: false,
    hasStorageBlobs: false,
    purgeOnDelete: true,
    transferOnUpgrade: true,
    exportPersonalData: true,
    exportKey: "meetingContexts",
  },
  {
    table: "meetingCompanionDevices",
    userIdIndex: "by_user_meeting",
    byThreadOnly: false,
    hasStorageBlobs: false,
    purgeOnDelete: true,
    transferOnUpgrade: true,
    exportPersonalData: true,
    exportKey: "meetingCompanionDevices",
  },
  {
    table: "meetingOutputRequests",
    userIdIndex: "by_user_meeting_created",
    byThreadOnly: false,
    hasStorageBlobs: false,
    purgeOnDelete: true,
    transferOnUpgrade: true,
    exportPersonalData: true,
    exportKey: "meetingOutputRequests",
  },
] as const satisfies readonly UserScopedTable[];
